### ISSUE TITLE
ImportError: cannot import name 'PermutedSequenceGenerator'

### ISSUE THREAD

**Issue by kevaday** [eladhoffer/seq2seq.pytorch#15]
When running main.py, I get the following error:
```Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from seq2seq import models, datasets
  File "seq2seq.pytorch\seq2seq\models\__init__.py", line 1, in <module>
    from .transformer import Transformer, TransformerAttentionDecoder, TransformerAttentionEncoder
  File "seq2seq.pytorch\seq2seq\models\transformer.py", line 6, in <module>
    from .seq2seq_base import Seq2Seq
  File "seq2seq.pytorch\seq2seq\models\seq2seq_base.py", line 8, in <module>
    from seq2seq.tools.beam_search import SequenceGenerator, PermutedSequenceGenerator
ImportError: cannot import name 'PermutedSequenceGenerator'
```

I'm not sure whether it needs to be imported for training to work.
Thanks

**Comment by AASHISHAG** [comment]
Any solution for this problem?
