### ISSUE TITLE
How do we use scripts under the train folder

### ISSUE THREAD

**Issue by liperrino** [eladhoffer/seq2seq.pytorch#8]
Hi. Please i would like to know how to train train these models. When i ran train_en_de.sh, i get errors:

Traceback (most recent call last):
  File "/media/vivien/A/NEW-SMT/seq2seq.pytorch-master/main.py", line 15, in <module>
    from seq2seq.tools.utils.log import setup_logging
ModuleNotFoundError: No module named 'seq2seq.tools.utils.log'
Traceback (most recent call last):
  File "/media/vivien/A/NEW-SMT/seq2seq.pytorch-master/main.py", line 15, in <module>
    from seq2seq.tools.utils.log import setup_logging
ModuleNotFoundError: No module named 'seq2seq.tools.utils.log'
Traceback (most recent call last):
  File "/media/vivien/A/NEW-SMT/seq2seq.pytorch-master/main.py", line 15, in <module>
    from seq2seq.tools.utils.log import setup_logging
ModuleNotFoundError: No module named 'seq2seq.tools.utils.log'
Traceback (most recent call last):
  File "/media/vivien/A/NEW-SMT/seq2seq.pytorch-master/main.py", line 15, in <module>
    from seq2seq.tools.utils.log import setup_logging
ModuleNotFoundError: No module named 'seq2seq.tools.utils.log'

**Comment by guyco87** [comment]
You should run the setup script before running anything else

python setup.py develop
